### ISSUE TITLE
Back to inventory option suggestion

### ISSUE THREAD

**Issue by Ultimushadow** [RealMegaMinds/ClickOpener#11]
I imagine most people use this mod to access their enderchests and shulker boxes without placing them down, which leads to a small problem when taking out items intended for armor slots or trinket slots added by other mods. I was wondering if you could add a small button that would take the player back to their inventory without having to close and open the GUI - personally, I feel like that action defeats the purpose of the mod. I think either adding a small "back to inventory" button either at the bottom of the gui, at the top next to the name of the gui you're in, or a keybind could work, but let me know what you think!

**Comment by Hoid2** [comment]
The reason I didn't add this before was because if you opened an inventory from a physical block, then one in your inventory, and then went back, there is no easy way to tell if the physical block attached to the first gui is still there (it could've been destroyed).

This wouldn't matter for your normal inventory, so I should be able to at least make that work.

**Comment by Ultimushadow** [comment]
Gotcha, that makes sense, to be honest I didn't really consider a full back button as a possibility anyways due to the sheer amount of back and forth I tend to do, I figured that would be a pain to cache. Going back to the players regular inventory though seemed like a much easier thing to do, and it solves closing and reopening inventories for cases with physical blocks too (like finding armor as loot but needing to exit out of the chest to actually put it on)
Minor problem but gui screen flashing annoys the crap out of me lol I would rather get everything done at once
Thanks for looking into it!

**Comment by Hoid2** [comment]
This is not possible. The player's inventory cannot be opened from the server. I could open a fake inventory where you would have access to armor slots but no crafting table. Would that work?

**Comment by Ultimushadow** [comment]
Ahh that makes sense, in that case yes that would be better since if you really needed to craft you can just access a crafting table in your inventory
Would this work for off-hand and mod added slots like Trinkets?

**Comment by Hoid2** [comment]
It would work for offhand. Compatibility for other mods wouldn't work automatically but could be added.

**Comment by Ultimushadow** [comment]
I think I'm safe to go ahead and close this honestly, as nice of a thought as the feature it, without adding clientside to the mod it seems like it's just going to be a hassle for you guys to add every single inventory compat. We'll just be stuck with hitting e twice and dealing with the screen flash
Thanks for taking this suggestion and trying to make it work! I appreciate the effort that goes into modding, especially a mod that has to deal with click events and inventory screens (I do not like modding screens lol)
