### ISSUE TITLE
Allow setting default clickType for all players

### ISSUE THREAD

**Issue by unilock** [RealMegaMinds/ClickOpener#13]
It seems that `clickType` must be manually configured by each player, without the ability to change its default value from `"RIGHT"`.

I expected the following `clickopener_player.json` to work:
```
{
    "clickType": "SHIFT_RIGHT"
}
```
...but I get the error `Failed to read configuration file: Failed parsing 'clickType' as UUID; at path $.`, likely because it's expecting a map of UUIDs to PlayerConfig objects.

I would like to be able to set a `clickType` that acts as the default value for every player, used when the player has not yet configured that option themselves. Currently, the default seems to be [hardcoded to `ClickType.RIGHT`](https://github.com/RealMegaMinds/ClickOpener/blob/1.20.2/src/main/java/megaminds/clickopener/PlayerConfigs.java#L20C42-L20C42).

**Comment by Hoid2** [comment]
Try this version https://modrinth.com/mod/clickopener/version/3.0.2+1.20.1. It adds a `defaultClickType` option in `clickopener.json`.

**Comment by unilock** [comment]
That works great, thanks!
