### ISSUE TITLE
ClickOpener can cause unexplained server crashes

### ISSUE THREAD

**Issue by xiaoyan2007** [RealMegaMinds/ClickOpener#15]
[crash-2024-02-02_23.12.52-server.txt](https://github.com/RealMegaMinds/ClickOpener/files/14141993/crash-2024-02-02_23.12.52-server.txt)
Hello, I'm xiaoyan2007, a player of ClickOpener mod. You mod is helpful to my game. But it has some problems now.
When I add ClickOpener to my server, it causes crush.(Minecraft 1.20.1 Fabric)
The server can successfully launch without removing other mod.
At the same environment(1.20.1 Fabric),same mods with client,The game launched successfully without any doubt.
Also, I've sent crush report which was provided from server to you.
I'm looking forward to you reply which is at  your convenience.

**Comment by xiaoyan2007** [comment]
Hello! I did some tests and find that some options of carpet AMS addition caused the crash.
I'm going to do more tests.
And here is the website of AMS:https://minecraft-ams.github.io/carpetamsaddition/Rules/

**Comment by Hoid2** [comment]
It is specifically the largeShulkerBox rule that causes issues. I'm still working on the fix for it.

**Comment by Hoid2** [comment]
This only affects versions of Carpet AMS 2.27.1+. If you use a version before that, it should be fine.

**Comment by xiaoyan2007** [comment]
:D Waiting for new version

**Comment by Hoid2** [comment]
This version should work https://modrinth.com/mod/clickopener/version/4.0.0-alpha+1.20.1
