### ISSUE TITLE
[Feature Request]: Compatibility with Reinforced Shulker Boxes

### ISSUE THREAD

**Issue by yesiam77** [RealMegaMinds/ClickOpener#3]
Great mod!
Any chance of adding compatibility with the following mod (and its add on)?
- [Reinforced Shulker Boxes](https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes)
- [Reinforced Shulker Boxes (Enderite Addon)](https://www.curseforge.com/minecraft/mc-mods/enderite-reinforced-storage)

It just adds extra shulker boxes with different sizes.

**Comment by Hoid2** [comment]
Sure I can look in into that

**Comment by Hoid2** [comment]
@yesiam77 Check out version [2.0.0](https://modrinth.com/mod/clickopener/version/2.0.0). You will just have to add each shulker box you want to enable into the [config](https://modrinth.com/mod/clickopener).
Let me know if you have any problems.
