### ISSUE TITLE
Items duplicate or disappear if you interact with them while dragging the container

### ISSUE THREAD

**Issue by FellowRabbit** [RealMegaMinds/ClickOpener#4]
If you click items into a Shulker Box while that Shulker Box is actively selected (as in you left-clicked on it to move it around), the items put into that Shulker Box will be deleted when you navigate out of that box.

Similarly, if you click items out of a Shulker Box while that Shulker Box is selected, the items you take out of that Shulker Box will still be in that Shulker Box as well as your inventory once you navigate out of that box.

A fix for the base 1.19 version of this mod would also be much appreciated.

**Comment by Hoid2** [comment]
A fix is in progress.

**Comment by Hoid2** [comment]
This should now be fixed in [2.0.1](https://modrinth.com/mod/clickopener/version/2.0.1)
