### ISSUE TITLE
Settings are not restored after restart

### ISSUE THREAD

**Issue by manuelgrabowski** [RealMegaMinds/ClickOpener#5]
I noticed something rather odd, even though the `clickopener.properties` file is getting written correctly and there is no exception when loading the file either, the settings aren't properly restored. I have to manually add the allowed items back after every restart.

Looking into the code, is it possible that [loadFromProperties()](https://github.com/RealMegaMinds/ClickOpener/blob/bc9930e05d6f186dc98e730f14a3ff105aab6a68/src/main/java/megaminds/clickopener/Config.java#L58) is missing a call to [readBlocks()](https://github.com/RealMegaMinds/ClickOpener/blob/bc9930e05d6f186dc98e730f14a3ff105aab6a68/src/main/java/megaminds/clickopener/Config.java#L64)? I might be missing something, but it looks like loading the config from file is only reading the key and the default value, but not the manually defined blocks.

**Comment by Hoid2** [comment]
That was totally the case. I don't know how I messed that up. Try https://modrinth.com/mod/clickopener/version/2.0.3+1.19.3

**Comment by manuelgrabowski** [comment]
Dang you're quick! :D Works like a charm, thanks! 👍
