### ISSUE TITLE
Shulker box enchantments not preserved after opening with ClickOpener

### ISSUE THREAD

**Issue by ghifari160** [RealMegaMinds/ClickOpener#6]
**Mod Version:** 2.0.4+1.19.4
**Fabric API Version:** 0.79.0+1.19.4
**Fabric Loader Version:** 0.14.19
**Minecraft Version:** 1.19.4 with experimental datapacks (update 1.20 and bundles)
**Java Version:**
```
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

The mod [EnchantedShulkers](https://modrinth.com/mod/enchantedshulkers) adds enchantments to shulker boxes. Even with ClickOpener installed, the enchantments are preserved once the shulker boxes are placed down and picked back up. However, if the boxes were opened inside the inventory UI using ClickOpenener, the enchantments are no longer preserved once placed down and retrieved. The enchantments are still there on the item itself until the boxes are placed down.

From what I noticed, it's because of the way NBT tags are stored for shulker boxes. EnchantedShulkers enchantments are stored under `Enchantments` _and_ `BlockEntityTag.Enchantments`. Once the box is placed down and retrieved, only tags under `BlockEntityTag` are preserved. Rather than replacing `BlockEntityTag.Items`, ClickOpener is replacing the _whole_ `BlockEntityTag` after the user closes the shulker box UI. I know this is the case because the `Enchantments` tag is still there but not the `BlockEntityTag.Enchantments` tag.

This issue is present _with and without_ the experimental datapacks. That is, the issue is present even on a clean Fabric server with just ClickOpener, EnchantedShulkers, and their dependencies installed.

**Comment by Hoid2** [comment]
Try out version [2.0.5](https://modrinth.com/mod/clickopener/version/2.0.5+1.19.4)
