### ISSUE TITLE
Allow using tags for "allowed blocks" in config

### ISSUE THREAD

**Issue by unilock** [RealMegaMinds/ClickOpener#9]
It would be nice if [tags](https://minecraft.fandom.com/wiki/Tag) could be used in the config to specify allowed items, instead of just full identifiers. For example:
```
anvil=true
chipped_anvil=true
damaged_anvil=true
```
could become simply
```
#anvil=true
```
(as the `#anvil` tag, present in vanilla Minecraft, contains `anvil`, `chipped_anvil`, and `damaged_anvil` already)

***

I was initially going to suggest this for shulker boxes, but it seems `#shulker_boxes` only exists as a *block* tag, not an *item* tag... maybe both types of tag could be supported? Or maybe only block tags, since that's what's more relevant here?  
(I'm not certain of the logistics of supporting block tags in an items-only context.)

**Comment by Hoid2** [comment]
I'll see what I can do.

**Comment by Hoid2** [comment]
@unilock 
Version [3.0.0](https://modrinth.com/mod/clickopener/version/3.0.0-alpha+1.20.1) adds this functionality. Block tags are prefixed by block (block#shulker_boxes) and item tags are prefixed by item (item#anvil).
